version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: php_invoices
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - mysql_network

volumes:
    mysql_data:

networks:
    mysql_network:
        driver: bridge
